-- MechaBot MySQL 8 schema for WAMP. Import this into a new `mechabot` database.
CREATE DATABASE IF NOT EXISTS mechabot CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mechabot;

CREATE TABLE users (
  id CHAR(36) PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL, phone VARCHAR(20) NULL, role ENUM('admin','client','mechanic') NOT NULL DEFAULT 'client',
  is_blocked BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE user_roles (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, role ENUM('admin','client','mechanic') NOT NULL, UNIQUE KEY user_role_unique (user_id, role), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE profiles (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL UNIQUE, full_name VARCHAR(100) NOT NULL, phone VARCHAR(20), avatar_url TEXT, is_blocked BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE mechanic_profiles (
  id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL UNIQUE, full_name VARCHAR(100), nida_number VARCHAR(40), email VARCHAR(255), phone VARCHAR(20), specialties JSON NOT NULL,
  garage_location VARCHAR(200), certification_urls JSON NULL, profile_image_url TEXT, approval_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending', is_online BOOLEAN NOT NULL DEFAULT FALSE,
  availability_status VARCHAR(20) NOT NULL DEFAULT 'available', rating DECIMAL(2,1) DEFAULT 0, total_reviews INT DEFAULT 0, experience_years INT DEFAULT 0, tier ENUM('silver','gold','diamond') DEFAULT 'silver', lat DOUBLE, lng DOUBLE,
  badge VARCHAR(100), is_blocked BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE mechanic_locations (id CHAR(36) PRIMARY KEY, mechanic_id CHAR(36) NOT NULL UNIQUE, latitude DOUBLE NOT NULL DEFAULT -6.7924, longitude DOUBLE NOT NULL DEFAULT 39.2083, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (mechanic_id) REFERENCES mechanic_profiles(id) ON DELETE CASCADE);
CREATE TABLE service_requests (id CHAR(36) PRIMARY KEY, client_id CHAR(36) NOT NULL, mechanic_id CHAR(36) NULL, category VARCHAR(100) NOT NULL, description TEXT, car_model VARCHAR(255), car_year VARCHAR(20), vehicle_size ENUM('small','medium','large') NOT NULL DEFAULT 'medium', client_lat DOUBLE NULL, client_lng DOUBLE NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (mechanic_id) REFERENCES users(id) ON DELETE SET NULL, INDEX request_client (client_id), INDEX request_mechanic_status (mechanic_id, status), INDEX request_client_location (client_lat, client_lng));
CREATE TABLE orders (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, mechanic_id CHAR(36) NOT NULL, description TEXT, problem TEXT, car_category VARCHAR(100), location JSON, status VARCHAR(30) NOT NULL DEFAULT 'pending', estimated_price INT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX orders_user (user_id), INDEX orders_mechanic_status (mechanic_id, status));
CREATE TABLE notifications (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, type VARCHAR(50) NOT NULL DEFAULT 'info', message TEXT NOT NULL, status ENUM('unread','read') NOT NULL DEFAULT 'unread', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX notification_user_status (user_id, status));
CREATE TABLE messages (id CHAR(36) PRIMARY KEY, request_id CHAR(36) NOT NULL, sender_id CHAR(36) NOT NULL, receiver_id CHAR(36) NOT NULL, message TEXT NOT NULL, status ENUM('unread','read') NOT NULL DEFAULT 'unread', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (request_id) REFERENCES service_requests(id) ON DELETE CASCADE, FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE, INDEX message_receiver_status (receiver_id, status));
CREATE TABLE mechanic_ratings (id CHAR(36) PRIMARY KEY, request_id CHAR(36) NOT NULL UNIQUE, client_id CHAR(36) NOT NULL, mechanic_id CHAR(36) NOT NULL, rating TINYINT NOT NULL, comment TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (request_id) REFERENCES service_requests(id) ON DELETE CASCADE, FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (mechanic_id) REFERENCES users(id) ON DELETE CASCADE, CHECK (rating BETWEEN 1 AND 5));
CREATE TABLE activity_logs (id CHAR(36) PRIMARY KEY, user_id CHAR(36) NULL, action VARCHAR(255) NOT NULL, table_name VARCHAR(100), record_id CHAR(36), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE service_prices (id CHAR(36) PRIMARY KEY, service_name_en VARCHAR(255) NOT NULL, service_name_sw VARCHAR(255) NOT NULL, car_size ENUM('small','medium','large') NOT NULL DEFAULT 'medium', estimated_price INT NOT NULL DEFAULT 0, problem TEXT, possible_cause TEXT, min_price INT, max_price INT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
